accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^profile/change-password$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')
]

tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from tutorial import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(phone='0')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=200, default='')
    city = models.CharField(max_length=50, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default = 0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

    check = UserProfileManager()

def create_profile(sender, **action):
    if action['created']:
        user_profile = UserProfile.objects.create(user=action['instance'])

post_save.connect(create_profile, sender=User)

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')

        if commit:
            user.save()

        return user

class UpdationForm(UserChangeForm):

    class Meta:
        model = User
        fields = {
            'first_name',
            'last_name',
            'email',
            'password'
        }

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import (
    RegistrationForm,
    UpdationForm
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
# def home(request):
#     data = {'name': ' ', 'age': [1,2,3,4,5]}
#     return render(request, 'accounts/home.html', data)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm
        return render(request, 'accounts/register.html', {'form': form})

def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = UpdationForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return render(request, 'accounts/edit_profile.html', {'form': form})
    else:
        form = UpdationForm(instance=request.user)
        return render(request, 'accounts/edit_profile.html', {'form': form})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, 'accounts/change_password.html', {'form': form})

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

tutorial/views.py
from django.shortcuts import redirect

# Create your views here.
def login_redirect(request):
    return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
<title>Change Password</title>
{% endblock %}
{% block body %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-default" type="submit">Change Password</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
<title>Update Profile</title>
{% endblock %}
{% block body %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-default" type="submit">Update</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block head %}
<title>Home Page</title>
{% endblock %}
{% block body %}
<div class="container">
  <h1 class="m-t-2">Welcome {{ name }}</h1>
  <ul>
    {% for a in age %}
    <li>{{ a }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block head %}
<title>Login Page</title>
{% endblock %}
{% block body %}
<div class="container">
  <h1> Login Form </h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-default" type="submit">Login</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block head %}
<title>Bye Bye</title>
{% endblock %} {% block body %}
<div class="container">
  <h1> You have logged out </h1>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block head %}
<title>Profile Page</title>
{% endblock %} {% block body %}
<div class="container">
  <p>Username: {{ user }}</p>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>
  <p>Description: {{ user.userprofile.description }}</p>
  <p>Website: {{ user.userprofile.website }}</p>
  <p>Phone: {{ user.userprofile.phone }}</p>
  <p>City: {{ user.userprofile.city }}</p>
  <img src="{{ user.userprofile.image.url }}" width="200 ">
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block head %}
<title>Register Page</title>
{% endblock %}
{% block body %}
<div class="container">
  <h1> Register Form </h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-default" type="submit">Register</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% block head %}
<title>Password Reset Page</title>
{% endblock %}
{% block body %}
<div class="container">
  <h1> Reset Password </h1>
  <p>
    Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-default" type="submit">Reset Password</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

accounts/templates/base.html
<html>
<head>
  <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  {% load static %}
  <!-- <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css"> -->
  <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" type="text/css">
  {% block head %}
  <title>Base</title>
  {% endblock %}
</head>
<body>
  <div class="container">
  </br>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Django</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
            <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
            <li><a href="{% url 'accounts:edit_profile' %}">Edit</a></li>
            <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
          {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:register' %}">Register</a></li>
          </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>
    {% block body %}
    {% endblock %}
  <div>
</body>
</html>